/** @type {import('@commitlint/types').UserConfig} */
module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "fix",
        "feat",
        "ux",
        "obs",
        "chore",
        "perf",
        "revert",
        "docs",
        "style",
        "refactor",
        "test",
        "build",
        "ci",
        "security",
      ],
    ],
    "scope-enum": [
      2,
      "always",
      [
        "trello",
        "integration",
        "contact",
        "company",
        "service",
        "event",
        "logging",
        "security",
        "repo",
      ],
    ],
    "type-case": [2, "always", "lower-case"],
    "type-empty": [2, "never"],
    "scope-case": [2, "always", "lower-case"],
    "scope-empty": [2, "never"],
    "subject-empty": [2, "never"],
    "subject-full-stop": [2, "never", "."],
    "header-max-length": [2, "always", 120],
  },
};
