<?php
/**
 * UpdateCardPosParameterOneOf
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MauticPlugin\MauticTrelloBundle\Openapi\lib
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mautic Trello API
 *
 * Create or update a card via the Trello API
 *
 * The version of the OpenAPI document: 0.1.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MauticPlugin\MauticTrelloBundle\Openapi\lib\Model;
use \MauticPlugin\MauticTrelloBundle\Openapi\lib\ObjectSerializer;

/**
 * UpdateCardPosParameterOneOf Class Doc Comment
 *
 * @category Class
 * @package  MauticPlugin\MauticTrelloBundle\Openapi\lib
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UpdateCardPosParameterOneOf
{
    /**
     * Possible values of this enum
     */
    public const TOP = 'top';

    public const BOTTOM = 'bottom';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::TOP,
            self::BOTTOM
        ];
    }
}


