<?php


/**
 * Aivie Trello API.
 *
 * Create or update a card via the Trello API
 *
 * The version of the OpenAPI document: 0.1.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MauticPlugin\AivieTrelloBundle\Openapi\lib\Model;

/**
 * UpdateCardPosParameterOneOf Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
class UpdateCardPosParameterOneOf
{
    /**
     * Possible values of this enum.
     */
    public const TOP = 'top';

    public const BOTTOM = 'bottom';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::TOP,
            self::BOTTOM,
        ];
    }
}
